[project]
drom-version = "0.1"

[project]
authors = ["sheosi <sertorbe@gmail.com>"]
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "sheosi <sertorbe@gmail.com>"
edition = "4.11.0"
license = "LGPL2"
min-edition = "4.07.0"
name = "Ocaml2D"
synopsis = "The Ocaml2D project"
version = "0.1.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."
# github-organization = "...github-organization..."

[project]
description = """\n
This is the description
of the Ocaml2D OCaml project
"""

[project]
skip = "test sphinx github docs ocamlformat ocp-indent"

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
# ...

[[package]]
dir = "src/Ocaml2D"
# edit 'src/Ocaml2D/package.toml' for package-specific options

