# Generated by "drom project"
.PHONY: all build build-deps fmt fmt-check install dev-deps test
.PHONY: clean distclean

DEV_DEPS := merlin ocamlformat odoc



all: build

build:
	./scripts/before.sh build
	opam exec -- dune build @install
	./scripts/copy-bin.sh Ocaml2D
	./scripts/after.sh build

build-deps:
	if ! [ -e _opam ]; then \
	   opam switch create . 4.11.0 ; \
	fi
	opam install ./*.opam --deps-only


fmt:
	opam exec -- dune build @fmt --auto-promote

fmt-check:
	opam exec -- dune build @fmt

install:
	opam pin -y --no-action -k path .
	opam install -y .

opam:
	opam pin -k path .

uninstall:
	opam uninstall .

dev-deps:
	opam install ./*.opam --deps-only --with-doc --with-test

test:
	./scripts/before.sh test
	opam exec -- dune build @runtest
	./scripts/after.sh test

clean:
	rm -rf _build
	./scripts/after.sh clean

distclean: clean
	rm -rf _opam _drom
	./scripts/after.sh distclean


